server:
  port: 8080
  servlet:
#    context giúp hệ thống định vị service này trong hệ thống microservice
    context-path: /student-management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/studentManagementDb"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: student-management

jwt:
  # KHÓA BÍ MẬT: Phải có độ dài lớn hơn 256 bits (32 bytes) cho HS256.
  # Khóa này phải là Base64 encoded hoặc một chuỗi dài an toàn.
  signer-key: "6e2a7f413eeab4768654fdb4585fb69f1c5d3ce920303ac335a765a22656b2f8"

  # Thời gian hiệu lực của Token (Đơn vị: GIÂY)
  validity: 3600 # 1 giờ